import type { AISummary } from '@/lib/types';

interface ClinicalNarrativeProps {
  summary: AISummary;
}

export function ClinicalNarrative({ summary }: ClinicalNarrativeProps) {
  const paragraphs = summary.clinicalNarrative.split('\n\n');

  return (
    <div className="space-y-6">
      <div className="prose prose-sm max-w-none">
        {paragraphs.map((paragraph, index) => (
          <p key={index} className="text-foreground leading-relaxed">
            {paragraph}
          </p>
        ))}
      </div>

      {summary.keyFindings.length > 0 && (
        <div className="rounded-lg border border-accent/20 bg-accent/5 p-4">
          <h4 className="mb-3 text-sm font-semibold text-accent">Key Findings</h4>
          <ul className="space-y-2">
            {summary.keyFindings.map((finding, index) => (
              <li key={index} className="flex items-start gap-2 text-sm text-foreground">
                <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-accent" />
                {finding}
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="flex flex-wrap items-center gap-x-2 gap-y-1 border-t border-border pt-4 text-xs text-muted-foreground">
        <span className="inline-flex items-center gap-1.5">
          <span className="h-2 w-2 rounded-full bg-muted-foreground/30" />
          Generated by Claude Opus 4.7 via Vercel AI Gateway
        </span>
        <span className="text-muted-foreground/50">·</span>
        <span>Pipeline orchestrated by WDK</span>
        {summary.reviewedBy && (
          <>
            <span className="text-muted-foreground/50">·</span>
            <span>Reviewed by {summary.reviewedBy}</span>
          </>
        )}
        <span className="text-muted-foreground/50">·</span>
        <span>{new Date(summary.generatedAt).toLocaleDateString()}</span>
      </div>
    </div>
  );
}
